// PAPI demo for the Bulletin Chain block-headroom SLI.

import { createClient } from "polkadot-api"
import { getWsProvider } from "polkadot-api/ws-provider/node"
// @ts-expect-error generated by `papi add bulletin -w <rpc>`
import { bulletin } from "@polkadot-api/descriptors"

const RPC = "wss://paseo-bulletin-rpc.polkadot.io"

const MAX_BLOCK_TX    = 512
const BYTE_CAP        = 8 * 1024 * 1024
const COUNT_THRESHOLD = MAX_BLOCK_TX * 0.8
const BYTES_THRESHOLD = BYTE_CAP        * 0.8

async function main(): Promise<void> {
  const client = createClient(getWsProvider(RPC))
  const api    = client.getTypedApi(bulletin)

  let goodBlocks = 0
  let badBlocks  = 0

  client.finalizedBlock$.subscribe(async (header: { hash: string; number: number }) => {
    const { hash, number: num } = header

    const events = await api.query.System.Events.getValue({ at: hash })

    const storedCount = events.filter(
      (e: any) =>
        e.event?.type === "TransactionStorage" &&
        e.event?.value?.type === "Stored",
    ).length

    const txs =
      (await api.query.TransactionStorage.Transactions.getValue(num, { at: hash })) ??
      []
    const storeBytes = txs.reduce((s: number, tx: any) => s + Number(tx.size), 0)

    const isGood = storedCount < COUNT_THRESHOLD && storeBytes < BYTES_THRESHOLD
    if (isGood) goodBlocks += 1
    else badBlocks += 1
    const sli = goodBlocks / (goodBlocks + badBlocks)

    console.log(
      JSON.stringify({
        block:   num,
        storedCount,
        storeBytes,
        verdict: isGood ? "good" : "bad",
        sli:     sli.toFixed(4),
      }),
    )
  })
}

main().catch((e: unknown) => {
  console.error(e)
  process.exit(1)
})
