// Copyright (C) Parity Technologies and the various Polkadot contributors, see CONTRIBUTING.md
// for a list of specific contributors.
// SPDX-License-Identifier: GPL-3.0-only

// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License version 3, as
// published by the Free Software Foundation.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

//! Autogenerated weights for `pallet_bulletin_hop_promotion`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 58.0.0
//! DATE: 2026-08-23, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `640a401451bb`, CPU: `Intel(R) Xeon(R) CPU @ 2.60GHz`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: 1024

// Executed Command:
// frame-omni-bencher
// v1
// benchmark
// pallet
// --extrinsic=*
// --runtime=target/production/wbuild/bulletin-westend-runtime/bulletin_westend_runtime.wasm
// --pallet=pallet_bulletin_hop_promotion
// --header=/__w/polkadot-bulletin-chain/polkadot-bulletin-chain/scripts/cmd/file_header.txt
// --output=./runtimes/bulletin-westend/src/weights
// --wasm-execution=compiled
// --steps=50
// --repeat=20
// --heap-pages=4096
// --min-duration
// 1

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::Weight};
use core::marker::PhantomData;

/// Weight functions for `pallet_bulletin_hop_promotion`.
pub struct WeightInfo<T>(PhantomData<T>);
impl<T: frame_system::Config> pallet_bulletin_hop_promotion::WeightInfo for WeightInfo<T> {
	/// Storage: `TransactionStorage::BlockTransactions` (r:1 w:0)
	/// Proof: `TransactionStorage::BlockTransactions` (`max_values`: Some(1), `max_size`: Some(44034), added: 44529, mode: `MaxEncodedLen`)
	/// Storage: `Timestamp::Now` (r:1 w:0)
	/// Proof: `Timestamp::Now` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `TransactionStorage::Authorizations` (r:1 w:0)
	/// Proof: `TransactionStorage::Authorizations` (`max_values`: None, `max_size`: Some(85), added: 2560, mode: `MaxEncodedLen`)
	/// The range of component `d` is `[1, 2097152]`.
	fn authorize_promote(d: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `390`
		//  Estimated: `45519`
		// Minimum execution time: 57_526_000 picoseconds.
		Weight::from_parts(57_725_000, 0)
			.saturating_add(Weight::from_parts(0, 45519))
			// Standard Error: 7
			.saturating_add(Weight::from_parts(1_424, 0).saturating_mul(d.into()))
			.saturating_add(T::DbWeight::get().reads(3))
	}
	/// Storage: `TransactionStorage::BlockTransactions` (r:1 w:0)
	/// Proof: `TransactionStorage::BlockTransactions` (`max_values`: Some(1), `max_size`: Some(44034), added: 44529, mode: `MaxEncodedLen`)
	/// Storage: `Timestamp::Now` (r:1 w:0)
	/// Proof: `Timestamp::Now` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `TransactionStorage::Authorizations` (r:1 w:0)
	/// Proof: `TransactionStorage::Authorizations` (`max_values`: None, `max_size`: Some(85), added: 2560, mode: `MaxEncodedLen`)
	/// Storage: `System::BlockHash` (r:1 w:0)
	/// Proof: `System::BlockHash` (`max_values`: None, `max_size`: Some(44), added: 2519, mode: `MaxEncodedLen`)
	/// The range of component `d` is `[1, 2097152]`.
	fn authorize_promote_v2(d: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `444`
		//  Estimated: `45519`
		// Minimum execution time: 61_944_000 picoseconds.
		Weight::from_parts(62_820_000, 0)
			.saturating_add(Weight::from_parts(0, 45519))
			// Standard Error: 6
			.saturating_add(Weight::from_parts(1_399, 0).saturating_mul(d.into()))
			.saturating_add(T::DbWeight::get().reads(4))
	}
}
