// Copyright (C) Parity Technologies and the various Polkadot contributors, see Contributions.md
// for a list of specific contributors.
// SPDX-License-Identifier: Apache-2.0

// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//! Autogenerated weights for `pallet_bulletin_transaction_storage`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 54.0.0
//! DATE: 2026-05-05, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `5da459f83d20`, CPU: `Intel(R) Xeon(R) CPU @ 2.60GHz`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: 1024

// Executed Command:
// frame-omni-bencher
// v1
// benchmark
// pallet
// --extrinsic=*
// --runtime=target/production/wbuild/bulletin-westend-runtime/bulletin_westend_runtime.wasm
// --pallet=pallet_bulletin_transaction_storage
// --header=/__w/polkadot-bulletin-chain/polkadot-bulletin-chain/scripts/cmd/file_header.txt
// --output=./runtimes/bulletin-westend/src/weights
// --wasm-execution=compiled
// --steps=50
// --repeat=20
// --heap-pages=4096
// --min-duration
// 1

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::Weight};
use core::marker::PhantomData;

/// Weight functions for `pallet_bulletin_transaction_storage`.
pub struct WeightInfo<T>(PhantomData<T>);
impl<T: frame_system::Config> pallet_bulletin_transaction_storage::WeightInfo for WeightInfo<T> {
	/// Storage: `TransactionStorage::BlockTransactions` (r:1 w:1)
	/// Proof: `TransactionStorage::BlockTransactions` (`max_values`: Some(1), `max_size`: Some(43522), added: 44017, mode: `MaxEncodedLen`)
	/// The range of component `l` is `[1, 2097152]`.
	fn store(l: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `203`
		//  Estimated: `45007`
		// Minimum execution time: 13_325_000 picoseconds.
		Weight::from_parts(13_851_000, 0)
			.saturating_add(Weight::from_parts(0, 45007))
			// Standard Error: 18
			.saturating_add(Weight::from_parts(6_913, 0).saturating_mul(l.into()))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `TransactionStorage::Transactions` (r:1 w:0)
	/// Proof: `TransactionStorage::Transactions` (`max_values`: None, `max_size`: Some(43542), added: 46017, mode: `MaxEncodedLen`)
	/// Storage: `TransactionStorage::BlockTransactions` (r:1 w:1)
	/// Proof: `TransactionStorage::BlockTransactions` (`max_values`: Some(1), `max_size`: Some(43522), added: 44017, mode: `MaxEncodedLen`)
	fn renew() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `333`
		//  Estimated: `47007`
		// Minimum execution time: 24_786_000 picoseconds.
		Weight::from_parts(26_645_000, 0)
			.saturating_add(Weight::from_parts(0, 47007))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `TransactionStorage::ProofChecked` (r:1 w:1)
	/// Proof: `TransactionStorage::ProofChecked` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	/// Storage: `TransactionStorage::RetentionPeriod` (r:1 w:0)
	/// Proof: `TransactionStorage::RetentionPeriod` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `TransactionStorage::Transactions` (r:1 w:0)
	/// Proof: `TransactionStorage::Transactions` (`max_values`: None, `max_size`: Some(43542), added: 46017, mode: `MaxEncodedLen`)
	/// Storage: `System::ParentHash` (r:1 w:0)
	/// Proof: `System::ParentHash` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	fn check_proof() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `43789`
		//  Estimated: `47007`
		// Minimum execution time: 74_481_000 picoseconds.
		Weight::from_parts(87_825_000, 0)
			.saturating_add(Weight::from_parts(0, 47007))
			.saturating_add(T::DbWeight::get().reads(4))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `TransactionStorage::Authorizations` (r:1 w:1)
	/// Proof: `TransactionStorage::Authorizations` (`max_values`: None, `max_size`: Some(77), added: 2552, mode: `MaxEncodedLen`)
	fn authorize_account() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `269`
		//  Estimated: `3542`
		// Minimum execution time: 17_479_000 picoseconds.
		Weight::from_parts(18_338_000, 0)
			.saturating_add(Weight::from_parts(0, 3542))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `TransactionStorage::Authorizations` (r:1 w:1)
	/// Proof: `TransactionStorage::Authorizations` (`max_values`: None, `max_size`: Some(77), added: 2552, mode: `MaxEncodedLen`)
	fn refresh_account_authorization() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `307`
		//  Estimated: `3542`
		// Minimum execution time: 13_583_000 picoseconds.
		Weight::from_parts(14_276_000, 0)
			.saturating_add(Weight::from_parts(0, 3542))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `TransactionStorage::Authorizations` (r:1 w:1)
	/// Proof: `TransactionStorage::Authorizations` (`max_values`: None, `max_size`: Some(77), added: 2552, mode: `MaxEncodedLen`)
	fn authorize_preimage() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `269`
		//  Estimated: `3542`
		// Minimum execution time: 12_497_000 picoseconds.
		Weight::from_parts(13_326_000, 0)
			.saturating_add(Weight::from_parts(0, 3542))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `TransactionStorage::Authorizations` (r:1 w:1)
	/// Proof: `TransactionStorage::Authorizations` (`max_values`: None, `max_size`: Some(77), added: 2552, mode: `MaxEncodedLen`)
	fn refresh_preimage_authorization() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `306`
		//  Estimated: `3542`
		// Minimum execution time: 12_952_000 picoseconds.
		Weight::from_parts(13_721_000, 0)
			.saturating_add(Weight::from_parts(0, 3542))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `TransactionStorage::Authorizations` (r:1 w:1)
	/// Proof: `TransactionStorage::Authorizations` (`max_values`: None, `max_size`: Some(77), added: 2552, mode: `MaxEncodedLen`)
	fn remove_expired_account_authorization() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `307`
		//  Estimated: `3542`
		// Minimum execution time: 19_256_000 picoseconds.
		Weight::from_parts(20_277_000, 0)
			.saturating_add(Weight::from_parts(0, 3542))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `TransactionStorage::Authorizations` (r:1 w:1)
	/// Proof: `TransactionStorage::Authorizations` (`max_values`: None, `max_size`: Some(77), added: 2552, mode: `MaxEncodedLen`)
	fn remove_expired_preimage_authorization() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `306`
		//  Estimated: `3542`
		// Minimum execution time: 14_287_000 picoseconds.
		Weight::from_parts(15_044_000, 0)
			.saturating_add(Weight::from_parts(0, 3542))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `TransactionStorage::BlockTransactions` (r:1 w:0)
	/// Proof: `TransactionStorage::BlockTransactions` (`max_values`: Some(1), `max_size`: Some(43522), added: 44017, mode: `MaxEncodedLen`)
	/// Storage: `TransactionStorage::Authorizations` (r:2 w:2)
	/// Proof: `TransactionStorage::Authorizations` (`max_values`: None, `max_size`: Some(77), added: 2552, mode: `MaxEncodedLen`)
	/// The range of component `l` is `[1, 2097152]`.
	fn validate_store(l: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `307`
		//  Estimated: `45007`
		// Minimum execution time: 18_373_000 picoseconds.
		Weight::from_parts(18_679_000, 0)
			.saturating_add(Weight::from_parts(0, 45007))
			// Standard Error: 14
			.saturating_add(Weight::from_parts(2_845, 0).saturating_mul(l.into()))
			.saturating_add(T::DbWeight::get().reads(3))
			.saturating_add(T::DbWeight::get().writes(2))
	}
	/// Storage: `TransactionStorage::Transactions` (r:1 w:0)
	/// Proof: `TransactionStorage::Transactions` (`max_values`: None, `max_size`: Some(43542), added: 46017, mode: `MaxEncodedLen`)
	/// Storage: `TransactionStorage::BlockTransactions` (r:1 w:0)
	/// Proof: `TransactionStorage::BlockTransactions` (`max_values`: Some(1), `max_size`: Some(43522), added: 44017, mode: `MaxEncodedLen`)
	/// Storage: `TransactionStorage::Authorizations` (r:2 w:2)
	/// Proof: `TransactionStorage::Authorizations` (`max_values`: None, `max_size`: Some(77), added: 2552, mode: `MaxEncodedLen`)
	fn validate_renew() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `487`
		//  Estimated: `47007`
		// Minimum execution time: 32_572_000 picoseconds.
		Weight::from_parts(34_718_000, 0)
			.saturating_add(Weight::from_parts(0, 47007))
			.saturating_add(T::DbWeight::get().reads(4))
			.saturating_add(T::DbWeight::get().writes(2))
	}
	/// Storage: `TransactionStorage::Transactions` (r:2 w:1)
	/// Proof: `TransactionStorage::Transactions` (`max_values`: None, `max_size`: Some(43542), added: 46017, mode: `MaxEncodedLen`)
	/// Storage: UNKNOWN KEY `0x0e7b504e5df47062be129a8958a7a1274e7b9012096b41c4eb3aaf947f6ea429` (r:0 w:1)
	/// Proof: UNKNOWN KEY `0x0e7b504e5df47062be129a8958a7a1274e7b9012096b41c4eb3aaf947f6ea429` (r:0 w:1)
	fn migrate_v2_to_v3_step() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `41726`
		//  Estimated: `93024`
		// Minimum execution time: 127_440_000 picoseconds.
		Weight::from_parts(132_048_000, 0)
			.saturating_add(Weight::from_parts(0, 93024))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(2))
	}
}
